name: Create a pull request for release.

on:
  push:
    branches: [staging]

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_TITLE: "[release]"
      BASE_BRANCH: main

    steps:
      - uses: actions/checkout@v4

      - name: Check if PR exists
        id: check_pr
        run: |
          echo "count=$(gh pr list -S ${PR_TITLE}' in:title' -B $BASE_BRANCH | wc -l)" >> $GITHUB_OUTPUT

      - name: Create release PR
        if: ${{ steps.check_pr.outputs.count == 0 }}
        run: |
          today=`TZ=JST date +"%Y-%m-%d"`
          gh pr create -B ${BASE_BRANCH} -t "${PR_TITLE} ${today}" -b "" -d
      - name: Set description
        run: |
          today=`TZ=JST date +"%Y-%m-%d"`
          pr_number=`gh pr list -S ${PR_TITLE}' in:title' -B $BASE_BRANCH --json number --jq '.[0].number'`
          pr=`gh api /repos/kufu/sample-product/pulls/${pr_number}/commits --paginate | jq '.[] | select(.commit.message | contains("Merge pull request")) | .commit.message' | awk '{print "- "$4}'`
          tmpfile=$(mktemp)
          cat << EOF > $tmpfile
          ## Related links
          $pr
          EOF
          gh pr edit staging --title "${PR_TITLE} ${today}"
          gh pr edit staging --body-file $tmpfile
          rm -f $tmpfile
